version: "3.9"
services:
  api:
    build:
      context: ./api
    image: wordle-api:latest
    ports: 
      - "8080:8080"
  wordle:
    build:
      context: ./wordle
    image: wordle:latest
    ports: 
      - "3000:3000"

